default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  port: 5433
  username: postgres
  password: docker

development:
  <<: *default
  database: api_campeonato_development

test:
  <<: *default
  database: api_campeonato_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>